### ISSUE TITLE
path/TryOn/VitonHD/test/cloth

### ISSUE THREAD

**Issue by hotick** [damo-vilab/AnyDoor#24]
DiffusionWrapper has 865.91 M params.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 5 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 1024 and using 5 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 5 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 1024 and using 5 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 1024 and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 1024 and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 1024 and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 1024 and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 1024 and using 20 heads.
Loaded model config from [configs/anydoor.yaml]
Loaded state_dict from [path/epoch=1-step=8687-pruned.ckpt]
Traceback (most recent call last):
  File "F:\AI\AnyDoor\run_inference.py", line 266, in <module>
    image_names = os.listdir(test_dir)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'path/TryOn/VitonHD/test/cloth'

**Comment by sailorsale** [comment]
building MemoryEfficientAttnBlock with 512 in_channels...
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 5 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 1024 and using 5 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 5 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 1024 and using 5 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 1024 and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 1024 and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 1024 and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 1024 and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 1024 and using 20 heads.
Loaded model config from [configs/anydoor.yaml]
Loaded state_dict from [path/epoch=1-step=8687.ckpt]
Traceback (most recent call last):
  File "D:\github\AnyDoor-for-windows-main\run_inference.py", line 266, in <module>
    image_names = os.listdir(test_dir)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'path/TryOn/VitonHD/test/cloth'
If you encounter this same problem, how should you solve it?

**Comment by XavierCHEN34** [comment]
Hi, 
 “'path/TryOn/VitonHD/test/cloth'” is just an example of the test dataset's path.  You should modify it to the real path.

**Comment by Aruen24** [comment]
how to deal?

**Comment by Flyingxin** [comment]
建立一个对应的文件夹，然后文件夹里面放图片，最好png格式

**Comment by chenjialin1104** [comment]
where can I download the example data of "/TryOn/VitonHD/test/cloth" ? may I have a .zip file so I can run influence conveniently Thanks.
