### ISSUE TITLE
invalid load key, 'v' when running run_inference.py

### ISSUE THREAD

**Issue by HackXieHao** [damo-vilab/AnyDoor#38]
Traceback (most recent call last):
  File "run_inference.py", line 28, in <module>
    model = create_model(model_config ).cpu()
  File "/data/ldap_home/hao.xie/github/AnyDoor/cldm/model.py", line 26, in create_model
    model = instantiate_from_config(config.model).cpu()
  File "/data/ldap_home/hao.xie/github/AnyDoor/ldm/util.py", line 81, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/data/ldap_home/hao.xie/github/AnyDoor/cldm/cldm.py", line 310, in __init__
    super().__init__(*args, **kwargs)
  File "/data/ldap_home/hao.xie/github/AnyDoor/ldm/models/diffusion/ddpm.py", line 565, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "/data/ldap_home/hao.xie/github/AnyDoor/ldm/models/diffusion/ddpm.py", line 632, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "/data/ldap_home/hao.xie/github/AnyDoor/ldm/util.py", line 81, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/data/ldap_home/hao.xie/github/AnyDoor/ldm/modules/encoders/modules.py", line 286, in __init__
    state_dict = torch.load(DINOv2_weight_path)
  File "/ldap_home/hao.xie/.conda/envs/anydoor/lib/python3.8/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/ldap_home/hao.xie/.conda/envs/anydoor/lib/python3.8/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by MnLgt** [comment]
Make sure you have git lfs installed before cloning the HF repo.
