### ISSUE TITLE
ModuleNotFoundError: No module named 'hubconf'

### ISSUE THREAD

**Issue by danyow-cheung** [damo-vilab/AnyDoor#79]
running `run_gradio_demo.py` worked fine one windows11 ,but got this error on linux .
Here are some info below
```
building MemoryEfficientAttnBlock with 512 in_channels...
Traceback (most recent call last):
  File "/home/danyow/code/ComfyUI-master/main_ad.py", line 5, in <module>
    from helper.anydoor_inference import inference_single_image
  File "/home/danyow/code/ComfyUI-master/helper/anydoor_inference.py", line 25, in <module>
    model = create_model(model_config ).cpu()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danyow/code/ComfyUI-master/helper/cldm/model.py", line 26, in create_model
    model = instantiate_from_config(config.model).cpu()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danyow/code/ComfyUI-master/helper/ldm/util.py", line 81, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danyow/code/ComfyUI-master/helper/cldm/cldm.py", line 312, in __init__
    super().__init__(*args, **kwargs)
  File "/home/danyow/code/ComfyUI-master/helper/ldm/models/diffusion/ddpm.py", line 566, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "/home/danyow/code/ComfyUI-master/helper/ldm/models/diffusion/ddpm.py", line 634, in instantiate_cond_stage
    model = instantiate_from_config(config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danyow/code/ComfyUI-master/helper/ldm/util.py", line 81, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danyow/code/ComfyUI-master/helper/ldm/util.py", line 89, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danyow/anaconda3/envs/comfy_v2/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danyow/code/ComfyUI-master/helper/ldm/modules/encoders/modules.py", line 273, in <module>
    import hubconf
ModuleNotFoundError: No module named 'hubconf'
```

**Comment by danyow-cheung** [comment]
I forgot the `diov2`folder ，my bad
